SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public;
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(1000) NOT NULL
);

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public;
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: reservations; Type: TABLE; Schema: public;
--

CREATE TABLE public.reservations (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    locked_by character varying(36),
    action_id bigint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    locked_at timestamp without time zone
);


--
-- Name: reservations_id_seq; Type: SEQUENCE; Schema: public;
--

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: actions; Type: TABLE; Schema: public;
--

CREATE TABLE public.actions (
    id bigint NOT NULL,
    type character varying(50) NOT NULL,
    params character varying(5000) NOT NULL,
    user_id bigint NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    last_modified_date timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: actions_id_seq; Type: SEQUENCE; Schema: public;
--

ALTER TABLE public.actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alarms; Type: TABLE; Schema: public;
--

CREATE TABLE public.alarms (
    id bigint NOT NULL,
    rule_id bigint,
    message character varying(5000) NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL
);

--
-- Name: alarms_id_seq; Type: SEQUENCE; Schema: public;
--

ALTER TABLE public.alarms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alarms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: reactions; Type: TABLE; Schema: public;
--

CREATE TABLE public.reactions (
    id bigint NOT NULL,
    rule_id bigint NOT NULL,
    name character varying(5000) NOT NULL,
    params character varying(5000) NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    last_modified_date timestamp without time zone DEFAULT now() NOT NULL
);

--
-- Name: reactions_id_seq; Type: SEQUENCE; Schema: public;
--

ALTER TABLE public.reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rules; Type: TABLE; Schema: public;
--

CREATE TABLE public.rules (
    id bigint NOT NULL,
    action_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    definition character varying(5000) NOT NULL,
    created_date timestamp without time zone DEFAULT now() NOT NULL,
    last_modified_date timestamp without time zone DEFAULT now() NOT NULL
);

--
-- Name: rules_id_seq; Type: SEQUENCE; Schema: public;
--

ALTER TABLE public.rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: actions reservations_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);

--
-- Name: actions actions_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_pkey PRIMARY KEY (id);


--
-- Name: alarms alarms_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.alarms
    ADD CONSTRAINT alarms_pkey PRIMARY KEY (id);


--
-- Name: reactions reactions_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.reactions
    ADD CONSTRAINT reactions_pkey PRIMARY KEY (id);


--
-- Name: rules rules_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.rules
    ADD CONSTRAINT rules_pkey PRIMARY KEY (id);


--
-- Name: rules fk_actions_rule_actions_id; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.rules
    ADD CONSTRAINT fk_actions_rule_actions_id FOREIGN KEY (action_id) REFERENCES public.actions(id);


--
-- Name: reactions fk_rule_alarm_rule_id; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.reactions
    ADD CONSTRAINT fk_rule_alarm_rule_id FOREIGN KEY (rule_id) REFERENCES public.rules(id);

